name: Build and Test ml-commons
# This workflow is triggered on pull requests and push to any branches
on:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  Build-ml:
    strategy:
      matrix:
        java: [11, 17]

    name: Build and Test MLCommons Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout MLCommons
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build and Run Tests
        run: |
          ./gradlew build

  Build-ml-windows:
    strategy:
      matrix:
        java: [11, 17]
    name: Build and Test MLCommons Plugin on Windows
    runs-on: windows-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # ml-commons
      - name: Checkout MLCommons
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build and Run Tests
        shell: bash
        run: |
          ./gradlew.bat build
